name: Gatling Performance Tests

on:
  push:
  workflow_dispatch:
    inputs:
      GATLING_REQUESTS_PER_SECOND:
        description: 'Number of requests per second'
        required: true
        default: 60
        type: number
      GATLING_DURATION_SECONDS:
        description: 'Duration in seconds'
        required: true
        default: 200
        type: number
      ACTIVATE_VIRTUAL_THREADS:
        description: 'Active the virtual threads of Java 21'
        required: true
        default: true
        type: boolean

env:
  GATLING_REQUESTS_PER_SECOND: ${{ inputs.GATLING_REQUESTS_PER_SECOND || '400' }}
  GATLING_DURATION_SECONDS: ${{ inputs.GATLING_DURATION_SECONDS || '60' }}
  ACTIVATE_VIRTUAL_THREADS: ${{ inputs.ACTIVATE_VIRTUAL_THREADS || 'true' }}

jobs:
  gatling-performance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Start Spring Boot Application
        run: mvn spring-boot:run -Dspring-boot.run.arguments="--spring.threads.virtual.enabled=${{ env.ACTIVATE_VIRTUAL_THREADS }}" &

      - name: Wait for Spring Boot to be ready
        run: |
          timeout=60
          url="http://localhost:8080/actuator/health"
          echo "Waiting for application to be ready at $url..."
          until curl -s $url --header "userId: github" | grep 'UP'; do
            ((timeout--))
            if [ $timeout -le 0 ]; then
              echo "Application did not start in time."
              exit 1
            fi
            sleep 1
          done

      - name: Run Gatling Tests
        env:
          GATLING_REQUESTS_PER_SECOND: ${{ env.GATLING_REQUESTS_PER_SECOND }}
          GATLING_DURATION_SECONDS: ${{ env.GATLING_DURATION_SECONDS }}
        run: mvn gatling:test -Dgatling.simulationClass=com.benjamin.parsy.vtsb.author.AuthorSimulation

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: gatling-results
          path: target/gatling